"""Settings. Env-overridable with the ``UFO_AGENT_`` prefix.

Released exes embed their real version via agent/_buildinfo.py (generated by CI
from the git tag). Source/editable installs report a "-dev" version.
"""

from __future__ import annotations

import platform

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

try:
    from ._buildinfo import BUILD_VERSION as VERSION
except ImportError:
    VERSION = "0.0.1-dev"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="UFO_AGENT_", env_file=".env", extra="ignore")

    device_name: str = Field(default_factory=platform.node)

    # Default control plane to pair against; override with UFO_AGENT_CONTROL_PLANE_URL.
    control_plane_url: str = "https://ufo-cp.fly.dev"

    # Control plane base URL stored after pairing.
    relay_url: str | None = None

    # Loopback-only local UI (no auth; can approve actions — never bind publicly).
    local_ui_host: str = "127.0.0.1"
    local_ui_port: int = 8766

    # POC: discover the control plane on the tailnet and auto-enroll (no code).
    tailnet_autopair: bool = True

    heartbeat_seconds: float = 20.0
    reconnect_min_seconds: float = 1.0
    reconnect_max_seconds: float = 30.0
