"""Settings. Env-overridable with the ``UFO_AGENT_`` prefix.

Released exes embed their real version via agent/_buildinfo.py (generated by CI
from the git tag). Source/editable installs report a "-dev" version.
"""

from __future__ import annotations

import platform

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

try:
    from ._buildinfo import BUILD_VERSION as VERSION
except ImportError:
    VERSION = "0.0.1-dev"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="UFO_AGENT_", env_file=".env", extra="ignore")

    device_name: str = Field(default_factory=platform.node)

    # Control plane base URL (http/https). Set during pairing.
    relay_url: str | None = None

    # Loopback-only local UI (no auth; can approve actions — never bind publicly).
    local_ui_host: str = "127.0.0.1"
    local_ui_port: int = 8766
